# Generated by Django 3.1.2 on 2021-09-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayactivity',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
