# Generated by Django 3.1.2 on 2021-09-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12', '0002_dayactivity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayactivity',
            name='duration',
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='login_hours',
            field=models.FloatField(default=0),
        ),
    ]
